name: Build and Deploy to WeChat CloudRun

on:
  push:
    branches: [ master ]  # 修改为当前使用的主分支名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: cd cloud-deploy/wxcloudrun-springboot && mvn clean package -DskipTests
        
      # 此步仅用于调试，实际部署由微信云托管自动完成
      - name: List files
        run: ls -la cloud-deploy/wxcloudrun-springboot/target 